meta_product_name: "TrainUp"
meta_title: "TrainUp - Trouve un coach et améliore tes performances !"
meta_description: "Des professionels spécialistes de ton sport pour développer tes compétences techniques, physiques et mentales"
meta_image: "banner.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
